// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrKitchen.Persistance.Data;

#nullable disable

namespace UrKitchen.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220929131649_setup the database and configurations")]
    partial class setupthedatabaseandconfigurations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrKitchen.Persistance.Models.Attendee", b =>
                {
                    b.Property<int>("InvitationId")
                        .HasColumnType("integer");

                    b.Property<int>("InvitedMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("InvitationId", "InvitedMemberId");

                    b.HasIndex("InvitedMemberId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.DinnerInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.InvitationMeal", b =>
                {
                    b.Property<int>("InvitationId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.HasKey("InvitationId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("InvitationMeals");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChiefId")
                        .HasColumnType("integer");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChiefId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChiefId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<bool>("Delievered")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DeliveryCost")
                        .HasColumnType("numeric");

                    b.Property<string>("DeliveryLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DelivryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ChiefId");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.OrderMeal", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("OrderMeals");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.Attendee", b =>
                {
                    b.HasOne("UrKitchen.Persistance.Models.DinnerInvitation", "Invitation")
                        .WithMany("Attendees")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrKitchen.Persistance.Models.User", "Invitedmember")
                        .WithMany("Attendees")
                        .HasForeignKey("InvitedMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitation");

                    b.Navigation("Invitedmember");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.DinnerInvitation", b =>
                {
                    b.HasOne("UrKitchen.Persistance.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.InvitationMeal", b =>
                {
                    b.HasOne("UrKitchen.Persistance.Models.DinnerInvitation", "Invitation")
                        .WithMany("InvitationMeals")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrKitchen.Persistance.Models.Meal", "Meal")
                        .WithMany("InvitationMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitation");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.Meal", b =>
                {
                    b.HasOne("UrKitchen.Persistance.Models.User", "Chief")
                        .WithMany("Meals")
                        .HasForeignKey("ChiefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chief");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.Order", b =>
                {
                    b.HasOne("UrKitchen.Persistance.Models.User", "Chief")
                        .WithMany("RequestedOrders")
                        .HasForeignKey("ChiefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrKitchen.Persistance.Models.User", "Client")
                        .WithMany("CreatedOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chief");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.OrderMeal", b =>
                {
                    b.HasOne("UrKitchen.Persistance.Models.Meal", "Meal")
                        .WithMany("OrderMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrKitchen.Persistance.Models.Order", "Order")
                        .WithMany("OrderMeals")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.DinnerInvitation", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("InvitationMeals");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.Meal", b =>
                {
                    b.Navigation("InvitationMeals");

                    b.Navigation("OrderMeals");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.Order", b =>
                {
                    b.Navigation("OrderMeals");
                });

            modelBuilder.Entity("UrKitchen.Persistance.Models.User", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("CreatedOrders");

                    b.Navigation("Meals");

                    b.Navigation("RequestedOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
